# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    metallb.yaml                                       :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cbach <cbach@student.42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/12/11 13:33:53 by cbach             #+#    #+#              #
#    Updated: 2021/04/23 23:30:21 by cbach            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      avoid-buggy-ips: true
      protocol: layer2
      auto-assign: true
      addresses:
      - 192.168.99.2-192.168.99.169
      - 192.168.99.171-192.168.99.254
