apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  selector:
    matchLabels:
      app: client
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: client
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: basic
      volumes:
      - name: calc-persistent-storage
        persistentVolumeClaim:
          claimName: calc-pvc
      containers:
      - name: client
        image: sfcdota/client
        imagePullPolicy: Always
        resources:
          requests:
            memory: "16Mi"
            cpu: "1m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        ports:
          - containerPort: 30001
        volumeMounts:
        - name: calc-persistent-storage
          mountPath: /ftps-files/
