apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  selector:
    matchLabels:
      app: client
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: client
    spec:
      volumes:
      - name: ftps-persistent-storage
        persistentVolumeClaim:
          claimName: ftps-pv-claim
      containers:
      - name: client
        image: sfcdota/client
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
          - containerPort: 30001
        volumeMounts:
        - name: ftps-persistent-storage
          mountPath: /ftps-files/
