apiVersion: apps/v1 #версия API для объекта Deployment
kind: Deployment #тип объекта
metadata: #мета информация объекта
  name: ftps #имя развертывания
spec: #спецификация желаемого поведения Deployment
  selector: #селектор для подов
    matchLabels: #удовлетворяющий меткам
      app: ftps #селектор по меткам app:ftps
  replicas: 1 #желаемое количество подов
  strategy: #стратегия развертывания для замены старых подов
    type: Recreate #тип стратегии. старые поды будут убиты перед созданием новых
  template: #шаблон подов, созданных через этот Deployment
    metadata:
      labels:
        app: ftps
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      volumes: #массив томов, которые могут быть монтированы контейнерами в подах
      - name: calc-persistent-storage #имя хранилища
        persistentVolumeClaim: #описание ссылки на PVC в текущем пространстве имен
          claimName: calc-pvc #имя PVC
      containers: #массив контейнеров пода
      - name: ftps #имя контейнера
        image: sfcdota/ftps #имя образа, используемого контейнером
        imagePullPolicy: Always
        resources: #описание системных ресурсов
          requests: #запросы ресурсов - начальное выделение ресурсов
            memory: "16Mi" #оперативная память
            cpu: "1m" #ядра процессора, которые делятся вплоть до одной тысячной ядра
          limits: #предел использования системных ресурсов
            memory: "256Mi"
            cpu: "500m"
        envFrom:
        - secretRef:
            name: accounts-secret
        volumeMounts: #массив томов пода для монтирования в файловую систему контейнеров
        - name: calc-persistent-storage #имя, совпадающее с соответствующим volume
          mountPath: /root/ #путь в контейнере в виде папки, по которому монтируется хранилище
        ports: #массив портов пода
          - containerPort: 21 #порт, который будет использоваться на ip пода
          - containerPort: 20 #носит описательный характере как EXPOSE в docker
          - containerPort: 35000 #внутри направляется слушающим контейнерам
          - containerPort: 35001
          - containerPort: 35002
