apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: basic
      containers:
      - name: grafana
        image: sfcdota/grafana
        imagePullPolicy: Always
        resources:
          requests:
            memory: "16Mi"
            cpu: "1m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        ports:
          - containerPort: 3000
