# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    grafana.yaml                                       :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cbach <cbach@student.42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/12/11 13:33:36 by cbach             #+#    #+#              #
#    Updated: 2021/04/26 04:50:29 by cbach            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: sfcdota/grafana
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
          - containerPort: 3000
