apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      volumes:
      - name: calc-persistent-storage
        persistentVolumeClaim:
          claimName: calc-pvc
      containers:
      - name: nginx
        image: sfcdota/nginx
        imagePullPolicy: Always
        resources:
          requests:
            memory: "16Mi"
            cpu: "1m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        ports:
          - containerPort: 80
          - containerPort: 443
        volumeMounts:
        - name: calc-persistent-storage
          mountPath: /ftps-files/csv-files
