# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    nginx.yaml                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cbach <cbach@student.42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/12/11 13:34:10 by cbach             #+#    #+#              #
#    Updated: 2021/04/25 13:06:19 by cbach            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: ftps-persistent-storage
        persistentVolumeClaim:
          claimName: ftps-pv-claim
      containers:
      - name: nginx
        image: sfcdota/nginx
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
          - containerPort: 443
          - containerPort: 22
        volumeMounts:
        - name: ftps-persistent-storage
          mountPath: /var/www/html/ftps_files
