# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    phpmyadmin.yaml                                    :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cbach <cbach@student.42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/12/11 13:34:19 by cbach             #+#    #+#              #
#    Updated: 2021/04/25 13:06:24 by cbach            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - image: sfcdota/phpmyadmin
        name: phpmyadmin
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          name: phpmyadmin
