---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dask-server-role
  namespace: default
rules:
- apiGroups:
  - ""  # indicates the core API group
  resources:
  - "pods"
  - "pods/portforward"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "delete"
- apiGroups:
  - ""  # indicates the core API group
  resources:
  - "pods/log"
  verbs:
  - "get"
  - "list"
- apiGroups:
  - "" # indicates the core API group
  resources:
  - "services"
  verbs:
  - "get"
  - "list"
  - "watch"
  # - "create"
  # - "delete"
- apiGroups:
  - "policy"  # indicates the policy API group
  resources:
  - "poddisruptionbudgets"
  verbs:
  - "get"
  - "list"
  - "watch"
  # - "create"
  # - "delete"
- apiGroups:
  - ""  # indicates the core API group
  resources:
  - "nodes"
  verbs:
  - "get"
  - "list"
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: dask-server-svc
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: dask-server-rolebind
    namespace: default
subjects:
    - kind: ServiceAccount
      name: dask-server-svc
      namespace: default
roleRef:
    kind: Role
    name: dask-server-role
    apiGroup: rbac.authorization.k8s.io
