apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: server
    spec:
      serviceAccountName: dask-server-svc
      volumes:
      - name: ftps-persistent-storage
        persistentVolumeClaim:
          claimName: ftps-pv-claim
      terminationGracePeriodSeconds: 60
      containers:
      - name: server
        image: sfcdota/server
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
          - containerPort: 30000
        volumeMounts:
        - name: ftps-persistent-storage
          mountPath: /ftps-files/