apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: server
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      serviceAccountName: dask-server-svc
      volumes:
      - name: calc-persistent-storage
        persistentVolumeClaim:
          claimName: calc-pvc
      terminationGracePeriodSeconds: 15
      containers:
      - name: server
        image: sfcdota/server
        imagePullPolicy: Always
        resources:
          requests:
            memory: "16Mi"
            cpu: "1m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
          - containerPort: 30000
        volumeMounts:
        - name: calc-persistent-storage
          mountPath: /ftps-files/
