# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    ftps.yaml                                          :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cbach <cbach@student.42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/12/11 13:33:39 by cbach             #+#    #+#              #
#    Updated: 2021/04/24 04:02:41 by cbach            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      volumes:
      - name: ftps-persistent-storage
        persistentVolumeClaim:
          claimName: ftps-pv-claim
      containers:
      - name: ftps
        image: sfcdota/ftps
        imagePullPolicy: Always
        env:
          - name: FTPS_USERNAME
            valueFrom:
              secretKeyRef:
                name: ftps-secret
                key: ftps-username
          - name: FTPS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ftps-secret
                key: ftps-password
          - name: FTPS_TEST_USERNAME
            valueFrom:
              secretKeyRef:
                name: ftps-secret
                key: ftps-test-username
          - name: FTPS_TEST_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ftps-secret
                key: ftps-test-password
        ports:
          - containerPort: 21
          - containerPort: 37000
          - containerPort: 37001
          - containerPort: 37002
          - containerPort: 37003
          - containerPort: 37004
          - containerPort: 37005
          - containerPort: 37006

        volumeMounts:
        - name: ftps-persistent-storage
          mountPath: /root/
