apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: server
    spec:
      serviceAccountName: dask-server-svc
      containers:
      - name: server
        image: sfcdota/server
        imagePullPolicy: Always
        ports:
          - containerPort: 30000