apiVersion: apps/v1
kind: Deployment
metadata:
  name: generator
spec:
  selector:
    matchLabels:
      app: generator
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: generator
    spec:
      volumes:
      - name: ftps-persistent-storage
        persistentVolumeClaim:
          claimName: ftps-pv-claim
      containers:
      - name: generator
        image: sfcdota/generator
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "100m"
        ports:
          - containerPort: 30010
        volumeMounts:
        - name: ftps-persistent-storage
          mountPath: /ftps-files/

