apiVersion: v1
kind: Service
metadata:
  name: client
  annotations:
    metallb.universe.tf/allow-shared-ip: shared-services
spec:
  selector:
    app: client
  type: LoadBalancer
  loadBalancerIP: 34.116.235.52
  ports:
    - name: client
      port: 22
