apiVersion: v1
kind: Service
metadata:
  name: dask
  annotations:
    metallb.universe.tf/allow-shared-ip: dvadvavosem
spec:
  selector:
    dask.org/cluster-name: dask # Cluster name will be added automatically
    dask.org/component: scheduler
  type: LoadBalancer
  loadBalancerIP: 34.116.235.52
  ports:
    - name: comm
      protocol: TCP
      port: 8786
      targetPort: 8786
    - name: dashboard
      protocol: TCP
      port: 8787
      targetPort: 8787

---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: dask
spec:
  minAvailable: 1
  selector:
    matchLabels:
      dask.org/cluster-name: dask # Cluster name will be added automatically
