# apiVersion: v1 #версия API для Service
# kind: Service #тип объекта
# metadata: #мета информация объекта
#   name: ftps #имя объекта
#   annotations: #аннотация для разделения адреса в MetalLB
#     metallb.universe.tf/allow-shared-ip: shared-services #произвольное значение
# spec: #спецификация желаемого состояние сервиса
#   selector: #селектор
#     app: ftps #по метке app:ftps
#   type: LoadBalancer #тип сервиса как балансировщик нагрузки
#   loadBalancerIP: 34.116.235.52
#   externalIPs: [34.116.235.52]
#   ports: #массив портов сервиса
#     - name: ftps #имя порта
#       protocol: TCP #протокол
#       port: 20 #внешний порт, по умолчанию targetPort имеет это же значение
#     - name: ftpsd
#       protocol: TCP
#       port: 21 #targetPort - внутренний порт, по которому можно связаться с контейнером
#     - name: ftps0
#       protocol: TCP
#       port: 35000
#     - name: ftps1
#       protocol: TCP
#       port: 35001
#     - name: ftps2
#       protocol: TCP
#       port: 35002
# ---


apiVersion: v1
kind: Service
metadata:
  name: dask
  annotations:
    metallb.universe.tf/allow-shared-ip: shared-services
spec:
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 34.116.235.52
  ports:
    - name: ftpsd
      protocol: TCP
      port: 21
      targetPort: 21
    - name: ftps
      protocol: TCP
      port: 20
      targetPort: 20
---
apiVersion: v1
kind: Service
metadata:
  name: dask
  annotations:
    metallb.universe.tf/allow-shared-ip: shared-services
spec:
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 34.116.235.52
  ports:
    - name: ftps-passive0
      protocol: TCP
      port: 35000
    - name: ftps-passive1
      protocol: TCP
      port: 35001
    - name: ftps-passive2
      protocol: TCP
      port: 35002
