apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: dvadvavosem
spec:
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 34.116.235.52
  externalIPs:
    - 34.116.235.52
  ports:
    - name: ftps
      protocol: TCP
      port: 20
    - name: ftpsd
      protocol: TCP
      port: 21
    - name: ftps0
      protocol: TCP
      port: 35000
    - name: ftps1
      protocol: TCP
      port: 35001
    - name: ftps2
      protocol: TCP
      port: 35002

