apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: dvadvavosem
spec:
  selector:
    app: nginx
  type: LoadBalancer
  loadBalancerIP: 34.116.235.52
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
