apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: dvadvavosem
spec:
  ports:
    - port: 5050
      protocol: TCP
  selector:
    app: wordpress
  type: LoadBalancer
  loadBalancerIP: 34.116.235.52
  externalIPs:
    - 34.116.235.52