apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: generator
spec:
  selector:
    matchLabels:
      app: generator
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: generator
    spec:
      volumes:
      - name: ftps-persistent-storage
        persistentVolumeClaim:
          claimName: ftps-pv-claim
      containers:
      - name: generator
        image: generator
        imagePullPolicy: Never
        resources:
          requests:
            memory: "0.5G"
            cpu: "0.5"
          limits:
            memory: "1G"
            cpu: "1"
        ports:
          - containerPort: 30010
        volumeMounts:
        - name: ftps-persistent-storage
          mountPath: /ftps-files/
      nodeSelector:
        type: main
---
apiVersion: v1
kind: Service
metadata:
  name: generator
spec:
  selector:
    app: generator
  ports:
    - name: generator
      protocol: TCP
      port: 30010
