apiVersion: v1 #версия API для PVC
kind: Secret #тип объекта
metadata: #мета информация объекта
  name: ftps-secret #имя объекта
type: Opaque #тип секрета. Opaque - произвольные пользовательские данные
data: #информация объекта по ключу-значению
  ftps-username: cm9vdA== #слева - ключ, справа - значение
  ftps-password: Y2JhY2g= #значение должно быть сериализовано в кодировке base64
  ftps-test-username: dGVzdA==
  ftps-test-password: cm9vdHRlc3Q=
  ftps-my-username: a2Vrd2FpdA==
  ftps-my-password: c2ZjZG90YQ==
# echo -n "passwd" | base64   MUST BE echo -n !!!!!!!!!!
