apiVersion: v1 #версия API для PVC
kind: Secret #тип объекта
metadata: #мета информация объекта
  name: accounts-secret #имя объекта
type: Opaque #тип секрета. Opaque - произвольные пользовательские данные
data: #информация объекта по ключу-значению
  username: cm9vdA== #слева - ключ, справа - значение
  password: Y2JhY2g= #значение должно быть сериализовано в кодировке base64
  test_username: dGVzdA==
  test_password: cm9vdHRlc3Q=
  my_username: a2Vrd2FpdA==
  my_password: c2ZjZG90YQ==
# echo -n "passwd" | base64   MUST BE echo -n !!!!!!!!!!
