apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: server
    spec:
      serviceAccountName: dask-server-svc
      volumes:
      - name: ftps-persistent-storage
        persistentVolumeClaim:
          claimName: ftps-pv-claim
      containers:
      - name: server
        image: server
        imagePullPolicy: Never
        ports:
          - containerPort: 30000
        volumeMounts:
        - name: ftps-persistent-storage
          mountPath: /ftps-files/
      nodeSelector:
        type: main
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  ports:
    - name: server
      protocol: TCP
      port: 30000
