apiVersion: v1
kind: PersistentVolume
metadata:
  name: calc-pv
spec:
  capacity:
    storage: 1T
  accessModes:
  - ReadWriteMany
  - ReadWriteOnce
  - ReadOnlyMany
  nfs:
    path: /dask_storage
    server: 10.77.73.202
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calc-pvc
spec:
  storageClassName: ""
  volumeName: calc-pv
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
    - ReadOnlyMany
  resources:
    requests:
      storage: 1T
